Dataset:
  type: 'tum'
  pcd_downsample: 128
  pcd_downsample_init: 128
  adaptive_pointsize: True
  point_size: 0.01
  single_process: False

Training:

  mapping_itr_num: 4
  gaussian_update_every: 150
  tracking_itr_num: 100
  track_start: 1500
  gaussian_update_offset: 50
  gaussian_th: 0.1
  gaussian_extent: 1.0
  gaussian_reset: 200000
  size_threshold: 5
  window_size: 4
  rgb_boundary_threshold: 0.01
  alpha: 0.5
  prune_mode: 'slam'
  post_process_iters: 26000

  spherical_harmonics: False

  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001

opt_params:
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 1.0
  position_lr_max_steps: 3000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.0010
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False
