inherit_from: configs/tum/tum.yaml
mode: mono

data:
  input_folder: datasets/tum/rgbd_dataset_freiburg1_desk
  output: datasets/tum/rgbd_dataset_freiburg1_desk/mono
  start_idx: 0
  post_processing: True
