inherit_from: configs/Replica/base_config.yaml

verbose: False
dataset: 'replica'
mode: 'rgbd'
stride: 1
mapping:
  device: "cuda:0"

tracking:
  device: "cuda:0"
  buffer: 128
  beta: 0.75
  warmup: 12
  upsample: True
  motion_filter:
    thresh: 4.0  # add as keyframe if avg flow >= 4.0 pixels
  multiview_filter:
    thresh: 0.01 # dpeth error < 0.01m
    visible_num: 2  # points viewed by at least 2 cameras
    kernel_size: inf
  frontend:
    radius: 1
    nms: 0
    thresh: 25.0  # only consider edge with avg flow < 25.0 pixels
    enable_loop: False
cam:
  ### original camera parameters
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  ### target/output camera settings, camera_size -> resize -> crop -> target_size
  H_edge: 0
  W_edge: 0
  H_out: 320
  W_out: 640
